-- PostgreSQL Database Schema for Tasks Project
-- Generated by Entity Framework Core Migration: InitialCreate
-- Database: tasks_project_db

-- ============================================
-- CREATE TABLES
-- ============================================

-- Users Table
CREATE TABLE IF NOT EXISTS "Users" (
"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "First_name" character varying(100) NOT NULL,
    "Last_name" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Wont_help" boolean NOT NULL
);

-- Categories Table (with self-referencing parent-child relationship)
CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Color" character varying(50) NOT NULL,
    "father_id" integer REFERENCES "Categories"("Id") ON DELETE RESTRICT
);

-- ChatSessions Table
CREATE TABLE IF NOT EXISTS "ChatSessions" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Title" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);

-- Tasks Table
CREATE TABLE IF NOT EXISTS "Tasks" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Task_Date" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "File_path" character varying(500) NOT NULL,
    "CategoryId" integer NOT NULL REFERENCES "Categories"("Id") ON DELETE CASCADE
);

-- Messages Table
CREATE TABLE IF NOT EXISTS "Messages" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "SessionId" integer NOT NULL REFERENCES "ChatSessions"("Id") ON DELETE CASCADE,
    "Role" character varying(50) NOT NULL,
    "Content" text NOT NULL,
  "CreatedAt" timestamp with time zone NOT NULL
);

-- FavoriteUserCategories Table (Junction table for Many-to-Many)
CREATE TABLE IF NOT EXISTS "FavoriteUserCategories" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "category_id" integer NOT NULL REFERENCES "Categories"("Id") ON DELETE CASCADE,
  UNIQUE("user_id", "category_id")
);

-- ============================================
-- CREATE INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS "IX_Categories_father_id" ON "Categories"("father_id");
CREATE INDEX IF NOT EXISTS "IX_ChatSessions_UserId" ON "ChatSessions"("UserId");
CREATE INDEX IF NOT EXISTS "IX_FavoriteUserCategories_category_id" ON "FavoriteUserCategories"("category_id");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_FavoriteUserCategories_user_id_category_id" ON "FavoriteUserCategories"("user_id", "category_id");
CREATE INDEX IF NOT EXISTS "IX_Messages_SessionId" ON "Messages"("SessionId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_CategoryId" ON "Tasks"("CategoryId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_user_id" ON "Tasks"("user_id");

-- ============================================
-- ENTITY RELATIONSHIPS SUMMARY
-- ============================================

/*
ONE-TO-MANY RELATIONSHIPS:
1. Users (1) → (Many) Tasks
   - Foreign Key: Tasks.user_id → Users.Id
   - Cascade Delete: ON DELETE CASCADE

2. Users (1) → (Many) ChatSessions
   - Foreign Key: ChatSessions.UserId → Users.Id
   - Cascade Delete: ON DELETE CASCADE

3. Users (1) → (Many) FavoriteUserCategories
   - Foreign Key: FavoriteUserCategories.user_id → Users.Id
   - Cascade Delete: ON DELETE CASCADE

4. Categories (1) → (Many) Tasks
   - Foreign Key: Tasks.CategoryId → Categories.Id
   - Cascade Delete: ON DELETE CASCADE

5. Categories (1) → (Many) FavoriteUserCategories
   - Foreign Key: FavoriteUserCategories.category_id → Categories.Id
   - Cascade Delete: ON DELETE CASCADE

6. ChatSessions (1) → (Many) Messages
   - Foreign Key: Messages.SessionId → ChatSessions.Id
   - Cascade Delete: ON DELETE CASCADE

SELF-REFERENCING RELATIONSHIP:
7. Categories (Parent) → Categories (Child)
   - Foreign Key: Categories.father_id → Categories.Id
   - Restrict Delete: ON DELETE RESTRICT (prevents deletion if children exist)

MANY-TO-MANY RELATIONSHIP (via Junction Table):
8. Users ↔ FavoriteUserCategories ↔ Categories
   - Unique Constraint: UNIQUE(user_id, category_id) prevents duplicate favorites
*/

-- ============================================
-- SAMPLE QUERIES
-- ============================================

-- Get all tasks for a user
SELECT t.* FROM "Tasks" t
WHERE t."user_id" = 1;

-- Get all favorite categories for a user
SELECT c.* FROM "Categories" c
INNER JOIN "FavoriteUserCategories" fuc ON c."Id" = fuc."category_id"
WHERE fuc."user_id" = 1;

-- Get all messages in a chat session
SELECT m.* FROM "Messages" m
WHERE m."SessionId" = 1
ORDER BY m."CreatedAt" DESC;

-- Get all child categories of a parent category
SELECT * FROM "Categories"
WHERE "father_id" = 1;

-- Get all tasks for a specific category
SELECT t.* FROM "Tasks" t
WHERE t."CategoryId" = 1;

-- Get user with all their tasks and chat sessions
SELECT u.*, 
       COUNT(DISTINCT t."Id") as task_count,
       COUNT(DISTINCT cs."Id") as chat_count
FROM "Users" u
LEFT JOIN "Tasks" t ON u."Id" = t."user_id"
LEFT JOIN "ChatSessions" cs ON u."Id" = cs."UserId"
WHERE u."Id" = 1
GROUP BY u."Id";

-- ============================================
-- DATA INTEGRITY CONSTRAINTS
-- ============================================

/*
1. PRIMARY KEYS:
   - All tables have integer primary keys with auto-increment

2. FOREIGN KEYS:
   - All foreign key relationships are enforced at database level
   - Cascade delete for most relationships
 - Restrict delete for self-referencing categories

3. UNIQUE CONSTRAINTS:
   - FavoriteUserCategories has unique constraint on (user_id, category_id)

4. NOT NULL CONSTRAINTS:
   - All required fields are marked as NOT NULL
   - Text content columns support up to TEXT type

5. FIELD LENGTH CONSTRAINTS:
   - First_name, Last_name: max 100 characters
   - Email: max 255 characters
   - Password: max 255 characters
   - Title (Task/ChatSession): max 200-255 characters
   - Color: max 50 characters
- Role: max 50 characters
   - File_path: max 500 characters
*/

-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- List all tables
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public';

-- List all foreign keys
SELECT
    tc.constraint_name,
    tc.table_name,
    kcu.column_name,
    ccu.table_name AS referenced_table_name,
    ccu.column_name AS referenced_column_name
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
    ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage AS ccu
    ON ccu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY';

-- Check table structure (example for Users)
SELECT column_name, data_type, character_maximum_length, is_nullable
FROM information_schema.columns
WHERE table_name = 'Users'
ORDER BY ordinal_position;

-- Count rows in each table
SELECT 'Users' as table_name, COUNT(*) as row_count FROM "Users"
UNION ALL
SELECT 'Tasks', COUNT(*) FROM "Tasks"
UNION ALL
SELECT 'Categories', COUNT(*) FROM "Categories"
UNION ALL
SELECT 'ChatSessions', COUNT(*) FROM "ChatSessions"
UNION ALL
SELECT 'Messages', COUNT(*) FROM "Messages"
UNION ALL
SELECT 'FavoriteUserCategories', COUNT(*) FROM "FavoriteUserCategories";
